<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Province;
use Illuminate\Database\Seeder;

class CountryCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Province::create(['name' => 'badakhshan']);
        Province::create(['name' => 'baghlan']);
        Province::create(['name' => 'kunduz']);
        Province::create(['name' => 'takhar']);
        Province::create(['name' => 'balkh']);
        Province::create(['name' => 'faryab']);
        Province::create(['name' => 'jawzjan']);
        Province::create(['name' => 'samangan']);
        Province::create(['name' => 'sar_e_pol']);
        Province::create(['name' => 'kabul']);
        Province::create(['name' => 'kapisa']);
        Province::create(['name' => 'logar']);
        Province::create(['name' => 'panjshir']);
        Province::create(['name' => 'parwan']);
        Province::create(['name' => 'wardak']);
        Province::create(['name' => 'kunar']);
        Province::create(['name' => 'laghman']);
        Province::create(['name' => 'nangarhar']);
        Province::create(['name' => 'nuristan']);
        Province::create(['name' => 'badghis']);
        Province::create(['name' => 'bamyan']);
        Province::create(['name' => 'farah']);
        Province::create(['name' => 'ghor']);
        Province::create(['name' => 'herat']);
        Province::create(['name' => 'ghazni']);
        Province::create(['name' => 'khost']);
        Province::create(['name' => 'paktya']);
        Province::create(['name' => 'paktika']);
        Province::create(['name' => 'daykundi']);
        Province::create(['name' => 'helmand']);
        Province::create(['name' => 'kandahar']);
        Province::create(['name' => 'nimroz']);
        Province::create(['name' => 'uruzgan']);
        Province::create(['name' => 'zabul']);

        District::create(['province_id'=> 1,'name' =>'arghanj_khwa']);
        District::create(['province_id'=> 1,'name' =>'argo']);
        District::create(['province_id'=> 1,'name' =>'baharak']);
        District::create(['province_id'=> 1,'name' =>'darayim']);
        District::create(['province_id'=> 1,'name' =>'fayzabad']);
        District::create(['province_id'=> 1,'name' =>'ishkashim']);
        District::create(['province_id'=> 1,'name' =>'jurm']);
        District::create(['province_id'=> 1,'name' =>'khash']);
        District::create(['province_id'=> 1,'name' =>'khwahan']);
        District::create(['province_id'=> 1,'name' =>'kishim']);
        District::create(['province_id'=> 1,'name' =>'kohistan']);
        District::create(['province_id'=> 1,'name' =>'kuf_ab']);
        District::create(['province_id'=> 1,'name' =>'kuran_wa_munjan']);
        District::create(['province_id'=> 1,'name' =>'ragh']);
        District::create(['province_id'=> 1,'name' =>'shahri_buzurg']);
        District::create(['province_id'=> 1,'name' =>'shekay']);
        District::create(['province_id'=> 1,'name' =>'shighnan']);
        District::create(['province_id'=> 1,'name' =>'shuhada']);
        District::create(['province_id'=> 1,'name' =>'tagab']);
        District::create(['province_id' => 1,'name' =>'tishkan']);
        District::create(['province_id' => 1,'name' =>'wakhan']);
        District::create(['province_id' => 1,'name' =>'wurduj']);
        District::create(['province_id' => 1,'name' =>'yaftali_sufla']);
        District::create(['province_id' => 1,'name' =>'yamgan']);
        District::create(['province_id' => 1,'name' =>'yawan']);
        District::create(['province_id' => 1,'name' =>'zebak']);
        District::create(['province_id' => 1,'name' =>'darwaz']);
        District::create(['province_id' => 1,'name' =>'darwaz_e_bala']);
        District::create(['province_id' => 2,'name' =>'andarab']);
        District::create(['province_id' => 2,'name' =>'baghlani_jadid']);
        District::create(['province_id' => 2,'name' =>'burka']);
        District::create(['province_id' => 2,'name' =>'dahana_i_ghuri']);
        District::create(['province_id' => 2,'name' =>'dih_salah']);
        District::create(['province_id' => 2,'name' =>'dushi']);
        District::create(['province_id' => 2,'name' =>'farang_wa_gharu']);
        District::create(['province_id' => 2,'name' =>'guzargahi_nur']);
        District::create(['province_id' => 2,'name' =>'khinjan']);
        District::create(['province_id' => 2,'name' =>'khost_wa_fereng']);
        District::create(['province_id' => 2,'name' =>'khwaja_hijran']);
        District::create(['province_id' => 2,'name' =>'nahrin']);
        District::create(['province_id' => 2,'name' =>'puli_hisar']);
        District::create(['province_id' => 2,'name' =>'puli_khumri']);
        District::create(['province_id' => 2,'name' =>'tala_wa_barfak']);
        District::create(['province_id' => 3,'name' =>'ali_abad']);
        District::create(['province_id' => 3,'name' =>'chahar_dara']);
        District::create(['province_id' => 3,'name' =>'imam_sahib']);
        District::create(['province_id' => 3,'name' =>'khan_abad']);
        District::create(['province_id' => 3,'name' =>'ku_kunduz']);
        District::create(['province_id' => 3,'name' =>'qalay_i_zal']);
        District::create(['province_id' => 3,'name' =>'dasht_e_archi']);
        District::create(['province_id' => 4,'name' =>'tk_baharak']);
        District::create(['province_id' => 4,'name' =>'bangi']);
        District::create(['province_id' => 4,'name' =>'chah_ab']);
        District::create(['province_id' => 4,'name' =>'chal']);
        District::create(['province_id' => 4,'name' =>'darqad']);
        District::create(['province_id' => 4,'name' =>'dashti_qala']);
        District::create(['province_id' => 4,'name' =>'farkhar']);
        District::create(['province_id' => 4,'name' =>'hazar_sumuch']);
        District::create(['province_id' => 4,'name' =>'ishkamish']);
        District::create(['province_id' => 4,'name' =>'kalafgan']);
        District::create(['province_id' => 4,'name' =>'khwaja_baha_wuddin']);
        District::create(['province_id' => 4,'name' =>'khwaja_ghar']);
        District::create(['province_id' => 4,'name' =>'namak_ab']);
        District::create(['province_id' => 4,'name' =>'rustaq']);
        District::create(['province_id' => 4,'name' =>'taluqan']);
        District::create(['province_id' => 4,'name' =>'warsaj']);
        District::create(['province_id' => 4,'name' =>'yangi_qala']);
        District::create(['province_id' => 5,'name' =>'bk_balkh']);
        District::create(['province_id' => 5,'name' =>'chahar_kint']);
        District::create(['province_id' => 5,'name' =>'chimtal']);
        District::create(['province_id' => 5,'name' =>'dawlatabad']);
        District::create(['province_id' => 5,'name' =>'dihdadi']);
        District::create(['province_id' => 5,'name' =>'kaldar']);
        District::create(['province_id' => 5,'name' =>'khulmi']);
        District::create(['province_id' => 5,'name' =>'kishindih']);
        District::create(['province_id' => 5,'name' =>'marmul']);
        District::create(['province_id' => 5,'name' =>'mazar_e_sharif']);
        District::create(['province_id' => 5,'name' =>'nahri_shahi']);
        District::create(['province_id' => 5,'name' =>'sholgara']);
        District::create(['province_id' => 5,'name' =>'shortepa']);
        District::create(['province_id' => 5,'name' =>'zari']);
        District::create(['province_id' => 5,'name' =>'shahrak_e_hayratan']);
        District::create(['province_id' => 5,'name' =>'chahar_bolak']);
        District::create(['province_id' => 6,'name' =>'almar']);
        District::create(['province_id' => 6,'name' =>'andkhoy']);
        District::create(['province_id' => 6,'name' =>'bilchiragh']);
        District::create(['province_id' => 6,'name' =>'dawlat_abad']);
        District::create(['province_id' => 6,'name' =>'gurziwan']);
        District::create(['province_id' => 6,'name' =>'khani_chahar_bagh']);
        District::create(['province_id' => 6,'name' =>'khwaja_sabz_posh']);
        District::create(['province_id' => 6,'name' =>'fr_kohistan']);
        District::create(['province_id' => 6,'name' =>'maymana']);
        District::create(['province_id' => 6,'name' =>'pashtun_kot']);
        District::create(['province_id' => 6,'name' =>'qaramqol']);
        District::create(['province_id' => 6,'name' =>'qaysar']);
        District::create(['province_id' => 6,'name' =>'qurghan']);
        District::create(['province_id' => 6,'name' =>'shirin_tagab']);
        District::create(['province_id' => 7,'name' =>'aqcha']);
        District::create(['province_id' => 7,'name' =>'darzab']);
        District::create(['province_id' => 7,'name' =>'jw_fayzabad']);
        District::create(['province_id' => 7,'name' =>'khamyab']);
        District::create(['province_id' => 7,'name' =>'khaniqa']);
        District::create(['province_id' => 7,'name' =>'khwaja_du_koh']);
        District::create(['province_id' => 7,'name' =>'mardyan']);
        District::create(['province_id' => 7,'name' =>'mingajik']);
        District::create(['province_id' => 7,'name' =>'qarqin']);
        District::create(['province_id' => 7,'name' =>'qush_tepa']);
        District::create(['province_id' => 7,'name' =>'shibirghan']);
        District::create(['province_id' => 8,'name' =>'aybak']);
        District::create(['province_id' => 8,'name' =>'dara_i_sufi_balla']);
        District::create(['province_id' => 8,'name' =>'dara_i_sufi_payan']);
        District::create(['province_id' => 8,'name' =>'feroz_nakhchir']);
        District::create(['province_id' => 8,'name' =>'hazrati_sultan']);
        District::create(['province_id' => 8,'name' =>'khuram_wa_sarbagh']);
        District::create(['province_id' => 8,'name' =>'ruyi_du_ab']);
        District::create(['province_id' => 9,'name' =>'balkhab']);
        District::create(['province_id' => 9,'name' =>'gosfandi']);
        District::create(['province_id' => 9,'name' =>'kohistanat']);
        District::create(['province_id' => 9,'name' =>'sangcharak']);
        District::create(['province_id' => 9,'name' =>'sar_e_pul']);
        District::create(['province_id' => 9,'name' =>'sayyad']);
        District::create(['province_id' => 9,'name' =>'sozma_qala']);
        District::create(['province_id' => 10,'name' =>'bagrami']);
        District::create(['province_id' => 10,'name' =>'chahar_asyab']);
        District::create(['province_id'=> 10,'name' =>'deh_sabz']);
        District::create(['province_id'=> 10,'name' =>'farza']);
        District::create(['province_id'=> 10,'name' =>'guldara']);
        District::create(['province_id'=> 10,'name' =>'istalif']);
        District::create(['province_id'=> 10,'name' =>'kb_kabul']);
        District::create(['province_id'=> 10,'name' =>'kalakan']);
        District::create(['province_id'=> 10,'name' =>'khaki_jabbar']);
        District::create(['province_id'=> 10,'name' =>'mir_bacha_kot']);
        District::create(['province_id'=> 10,'name' =>'mussahi']);
        District::create(['province_id'=> 10,'name' =>'paghman']);
        District::create(['province_id'=> 10,'name' =>'qarabagh']);
        District::create(['province_id'=> 10,'name' =>'shakardara']);
        District::create(['province_id'=> 10,'name' =>'surobi']);
        District::create(['province_id'=> 11,'name' =>'alasay']);
        District::create(['province_id'=> 11,'name' =>'hesa_awal_kohistan']);
        District::create(['province_id'=> 11,'name' =>'hesa_duwum_kohistan']);
        District::create(['province_id'=> 11,'name' =>'koh_band']);
        District::create(['province_id'=> 11,'name' =>'mahmud_raqi']);
        District::create(['province_id'=> 11,'name' =>'nijrab']);
        District::create(['province_id'=> 11,'name' =>'kp_tagab']);
        District::create(['province_id'=> 12,'name' =>'azra']);
        District::create(['province_id'=> 12,'name' =>'baraki_barak']);
        District::create(['province_id'=> 12,'name' =>'charkh']);
        District::create(['province_id'=> 12,'name' =>'kharwar']);
        District::create(['province_id'=> 12,'name' =>'khoshi']);
        District::create(['province_id'=> 12,'name' =>'mohammad_agha']);
        District::create(['province_id'=> 12,'name' =>'pul_i_alam']);
        District::create(['province_id'=> 13,'name' =>'anaba']);
        District::create(['province_id'=> 13,'name' =>'bazarak']);
        District::create(['province_id'=> 13,'name' =>'darah']);
        District::create(['province_id'=> 13,'name' =>'paryan']);
        District::create(['province_id'=> 13,'name' =>'rokha']);
        District::create(['province_id'=> 13,'name' =>'shotul']);
        District::create(['province_id'=> 13,'name' =>'hisa_i_awal']);
        District::create(['province_id'=> 14,'name' =>'bagram']);
        District::create(['province_id'=> 14,'name' =>'chaharikar']);
        District::create(['province_id'=> 14,'name' =>'jabal_saraj']);
        District::create(['province_id'=> 14,'name' =>'kohi_safi']);
        District::create(['province_id'=> 14,'name' =>'salang']);
        District::create(['province_id'=> 14,'name' =>'sayed_khel']);
        District::create(['province_id'=> 14,'name' =>'shekh_ali']);
        District::create(['province_id'=> 14,'name' =>'surkhi_parsa']);
        District::create(['province_id'=> 14,'name' =>'hisa_e_awale_kohistanat']);
        District::create(['province_id'=> 14,'name' =>'syah_gerd']);
        District::create(['province_id'=> 15,'name' =>'chaki_wardak']);
        District::create(['province_id'=> 15,'name' =>'day_mirdad']);
        District::create(['province_id'=> 15,'name' =>'hisa_i_awali_bihsud']);
        District::create(['province_id'=> 15,'name' =>'jaghatu']);
        District::create(['province_id'=> 15,'name' =>'jalrez']);
        District::create(['province_id'=> 15,'name' =>'markazi_bihsud']);
        District::create(['province_id'=> 15,'name' =>'maydan_shahr']);
        District::create(['province_id'=> 15,'name' =>'nirkh']);
        District::create(['province_id'=> 15,'name' =>'saydabad']);
        District::create(['province_id'=> 16,'name' =>'asadabad']);
        District::create(['province_id'=> 16,'name' =>'bar_kunar']);
        District::create(['province_id'=> 16,'name' =>'chapa_dara']);
        District::create(['province_id'=> 16,'name' =>'chawkay']);
        District::create(['province_id'=> 16,'name' =>'dangam']);
        District::create(['province_id'=> 16,'name' =>'dara_i_pech']);
        District::create(['province_id'=> 16,'name' =>'ghaziabad']);
        District::create(['province_id'=> 16,'name' =>'khas_kunar']);
        District::create(['province_id'=> 16,'name' =>'marawara']);
        District::create(['province_id'=> 16,'name' =>'narang_wa_badil']);
        District::create(['province_id'=> 16,'name' =>'nari']);
        District::create(['province_id'=> 16,'name' =>'nurgal']);
        District::create(['province_id'=> 16,'name' =>'shaygal_wa_shiltan']);
        District::create(['province_id'=> 16,'name' =>'sirkanay']);
        District::create(['province_id'=> 16,'name' =>'wata_pur']);
        District::create(['province_id'=> 17,'name' =>'alingar']);
        District::create(['province_id'=> 17,'name' =>'alishing']);
        District::create(['province_id'=> 17,'name' =>'dawlat_shah']);
        District::create(['province_id'=> 17,'name' =>'mihtarlam']);
        District::create(['province_id'=> 17,'name' =>'qarghayi']);
        District::create(['province_id'=> 18,'name' =>'achin']);
        District::create(['province_id'=> 18,'name' =>'bati_kot']);
        District::create(['province_id'=> 18,'name' =>'behsud']);
        District::create(['province_id'=> 18,'name' =>'chaparhar']);
        District::create(['province_id'=> 18,'name' =>'dara_i_nur']);
        District::create(['province_id'=> 18,'name' =>'dih_bala']);
        District::create(['province_id'=> 18,'name' =>'dur_baba']);
        District::create(['province_id'=> 18,'name' =>'goshta']);
        District::create(['province_id'=> 18,'name' =>'hisarak']);
        District::create(['province_id'=> 18,'name' =>'jalalabad']);
        District::create(['province_id'=> 18,'name' =>'kama']);
        District::create(['province_id'=> 18,'name' =>'khogyani']);
        District::create(['province_id'=> 18,'name' =>'kot']);
        District::create(['province_id'=> 18,'name' =>'kuz_kunar']);
        District::create(['province_id'=> 18,'name' =>'lal_pur']);
        District::create(['province_id'=> 18,'name' =>'muhmand_dara']);
        District::create(['province_id'=> 18,'name' =>'nazyan']);
        District::create(['province_id'=> 18,'name' =>'pachir_wa_agam']);
        District::create(['province_id'=> 18,'name' =>'rodat']);
        District::create(['province_id'=> 18,'name' =>'sherzad']);
        District::create(['province_id'=> 18,'name' =>'shinwar']);
        District::create(['province_id'=> 18,'name' =>'surkh_rod']);
        District::create(['province_id'=> 19,'name' =>'bargi_matal']);
        District::create(['province_id'=> 19,'name' =>'du_ab']);
        District::create(['province_id'=> 19,'name' =>'kamdesh']);
        District::create(['province_id'=> 19,'name' =>'mandol']);
        District::create(['province_id'=> 19,'name' =>'nurgaram']);
        District::create(['province_id'=> 19,'name' =>'parun']);
        District::create(['province_id'=> 19,'name' =>'wama']);
        District::create(['province_id'=> 19,'name' =>'waygal']);
        District::create(['province_id'=> 20,'name' =>'ab_kamari']);
        District::create(['province_id'=> 20,'name' =>'ghormach']);
        District::create(['province_id'=> 20,'name' =>'jawand']);
        District::create(['province_id'=> 20,'name' =>'muqur']);
        District::create(['province_id'=> 20,'name' =>'murghab']);
        District::create(['province_id'=> 20,'name' =>'qadis']);
        District::create(['province_id'=> 20,'name' =>'qala_i_naw']);
        District::create(['province_id'=> 21,'name' =>'bm_bamyan']);
        District::create(['province_id'=> 21,'name' =>'kahmard']);
        District::create(['province_id'=> 21,'name' =>'panjab']);
        District::create(['province_id'=> 21,'name' =>'sayghan']);
        District::create(['province_id'=> 21,'name' =>'shibar']);
        District::create(['province_id'=> 21,'name' =>'waras']);
        District::create(['province_id'=> 21,'name' =>'yakawlang']);
        District::create(['province_id'=> 22,'name' =>'anar_dara']);
        District::create(['province_id'=> 22,'name' =>'bakwa']);
        District::create(['province_id'=> 22,'name' =>'bala_buluk']);
        District::create(['province_id'=> 22,'name' =>'fr_farah']);
        District::create(['province_id'=> 22,'name' =>'gulistan']);
        District::create(['province_id'=> 22,'name' =>'khaki_safed']);
        District::create(['province_id'=> 22,'name' =>'lash_wa_juwayn']);
        District::create(['province_id'=> 22,'name' =>'pur_chaman']);
        District::create(['province_id'=> 22,'name' =>'pusht_rod']);
        District::create(['province_id'=> 22,'name' =>'qala_i_kah']);
        District::create(['province_id'=> 22,'name' =>'shib_koh']);
        District::create(['province_id'=> 23,'name' =>'chaghcharan']);
        District::create(['province_id'=> 23,'name' =>'charsada']);
        District::create(['province_id'=> 23,'name' =>'dawlat_yar']);
        District::create(['province_id'=> 23,'name' =>'du_layna']);
        District::create(['province_id'=> 23,'name' =>'lal_wa_sarjangal']);
        District::create(['province_id'=> 23,'name' =>'pasaband']);
        District::create(['province_id'=> 23,'name' =>'saghar']);
        District::create(['province_id'=> 23,'name' =>'shahrak']);
        District::create(['province_id'=> 23,'name' =>'taywara']);
        District::create(['province_id'=> 23,'name' =>'tulak']);
        District::create(['province_id'=> 24,'name' =>'adraskan']);
        District::create(['province_id'=> 24,'name' =>'chishti_sharif']);
        District::create(['province_id'=> 24,'name' =>'farsi']);
        District::create(['province_id'=> 24,'name' =>'ghoryan']);
        District::create(['province_id'=> 24,'name' =>'gulran']);
        District::create(['province_id'=> 24,'name' =>'guzara']);
        District::create(['province_id'=> 24,'name' =>'hr_herat']);
        District::create(['province_id'=> 24,'name' =>'injil']);
        District::create(['province_id'=> 24,'name' =>'karukh']);
        District::create(['province_id'=> 24,'name' =>'kohsan']);
        District::create(['province_id'=> 24,'name' =>'kushk']);
        District::create(['province_id'=> 24,'name' =>'kushki_kuhna']);
        District::create(['province_id'=> 24,'name' =>'obe']);
        District::create(['province_id'=> 24,'name' =>'pashtun_zarghun']);
        District::create(['province_id'=> 24,'name' =>'shindand']);
        District::create(['province_id'=> 24,'name' =>'zinda_jan']);
        District::create(['province_id'=> 25,'name' =>'ab_band']);
        District::create(['province_id'=> 25,'name' =>'ajristan']);
        District::create(['province_id'=> 25,'name' =>'andar']);
        District::create(['province_id'=> 25,'name' =>'dih_yak']);
        District::create(['province_id'=> 25,'name' =>'gelan']);
        District::create(['province_id'=> 25,'name' =>'giro']);
        District::create(['province_id'=> 25,'name' =>'jaghuri']);
        District::create(['province_id'=> 25,'name' =>'khwaja_umari']);
        District::create(['province_id'=> 25,'name' =>'malistan']);
        District::create(['province_id'=> 25,'name' =>'gz_muqur']);
        District::create(['province_id'=> 25,'name' =>'nawa']);
        District::create(['province_id'=> 25,'name' =>'nawur']);
        District::create(['province_id'=> 25,'name' =>'gz_qarabagh']);
        District::create(['province_id'=> 25,'name' =>'rashidan']);
        District::create(['province_id'=> 25,'name' =>'waghaz']);
        District::create(['province_id'=> 25,'name' =>'zana_khan']);
        District::create(['province_id'=> 25,'name' =>'wali_muhammadi_shahid']);
        District::create(['province_id'=> 26,'name' =>'bak']);
        District::create(['province_id'=> 26,'name' =>'gurbuz']);
        District::create(['province_id'=> 26,'name' =>'jaji_maydan']);
        District::create(['province_id'=> 26,'name' =>'mandozai']);
        District::create(['province_id'=> 26,'name' =>'musa_khel']);
        District::create(['province_id'=> 26,'name' =>'nadir_shah_kot']);
        District::create(['province_id'=> 26,'name' =>'qalandar']);
        District::create(['province_id'=> 26,'name' =>'sabari']);
        District::create(['province_id'=> 26,'name' =>'shamal']);
        District::create(['province_id'=> 26,'name' =>'spera']);
        District::create(['province_id'=> 26,'name' =>'tani']);
        District::create(['province_id'=> 26,'name' =>'tere_zayi']);
        District::create(['province_id'=> 26,'name' =>'matun_shar']);
        District::create(['province_id'=> 27,'name' =>'ahmadabad']);
        District::create(['province_id'=> 27,'name' =>'chamkani']);
        District::create(['province_id'=> 27,'name' =>'dand_wa_patan']);
        District::create(['province_id'=> 27,'name' =>'gardez']);
        District::create(['province_id'=> 27,'name' =>'lazha_ahmad_khel']);
        District::create(['province_id'=> 27,'name' =>'sayed_karam']);
        District::create(['province_id'=> 27,'name' =>'shwak']);
        District::create(['province_id'=> 27,'name' =>'zurmat']);
        District::create(['province_id'=> 27,'name' =>'ali_khel']);
        District::create(['province_id'=> 27,'name' =>'zadran']);
        District::create(['province_id'=> 28,'name' =>'barmal']);
        District::create(['province_id'=> 28,'name' =>'dila']);
        District::create(['province_id'=> 28,'name' =>'gayan']);
        District::create(['province_id'=> 28,'name' =>'gomal']);
        District::create(['province_id'=> 28,'name' =>'jani_khel']);
        District::create(['province_id'=> 28,'name' =>'nika']);
        District::create(['province_id'=> 28,'name' =>'omna']);
        District::create(['province_id'=> 28,'name' =>'sar_hawza']);
        District::create(['province_id'=> 28,'name' =>'sarobi']);
        District::create(['province_id'=> 28,'name' =>'sharan']);
        District::create(['province_id'=> 28,'name' =>'terwa']);
        District::create(['province_id'=> 28,'name' =>'urgun']);
        District::create(['province_id'=> 28,'name' =>'waza_khwa']);
        District::create(['province_id'=> 28,'name' =>'wor_mamay']);
        District::create(['province_id'=> 28,'name' =>'yahya_khel']);
        District::create(['province_id'=> 28,'name' =>'yosuf_khel']);
        District::create(['province_id'=> 28,'name' =>'zarghun_shahr']);
        District::create(['province_id'=> 28,'name' =>'ziruk']);
        District::create(['province_id'=> 28,'name' =>'zulmat']);
        District::create(['province_id'=> 29,'name' =>'gizab']);
        District::create(['province_id'=> 29,'name' =>'ishtarlay']);
        District::create(['province_id'=> 29,'name' =>'kajran']);
        District::create(['province_id'=> 29,'name' =>'khadir']);
        District::create(['province_id'=> 29,'name' =>'kiti']);
        District::create(['province_id'=> 29,'name' =>'miramor']);
        District::create(['province_id'=> 29,'name' =>'nili']);
        District::create(['province_id'=> 29,'name' =>'sangtakht']);
        District::create(['province_id'=> 29,'name' =>'shahristan']);
        District::create(['province_id'=> 30,'name' =>'baghran']);
        District::create(['province_id'=> 30,'name' =>'dishu']);
        District::create(['province_id'=> 30,'name' =>'garmsir']);
        District::create(['province_id'=> 30,'name' =>'kajaki']);
        District::create(['province_id'=> 30,'name' =>'lashkargah']);
        District::create(['province_id'=> 30,'name' =>'musa_qala']);
        District::create(['province_id'=> 30,'name' =>'nad_ali']);
        District::create(['province_id'=> 30,'name' =>'nawa_i_barakzayi']);
        District::create(['province_id'=> 30,'name' =>'nawzad']);
        District::create(['province_id'=> 30,'name' =>'sangin']);
        District::create(['province_id'=> 30,'name' =>'washir']);
        District::create(['province_id'=> 30,'name' =>'nahr_e_saraj']);
        District::create(['province_id'=> 31,'name' =>'arghandab']);
        District::create(['province_id'=> 31,'name' =>'arghistan']);
        District::create(['province_id'=> 31,'name' =>'daman']);
        District::create(['province_id'=> 31,'name' =>'ghorak']);
        District::create(['province_id'=> 31,'name' =>'kn_kandahar']);
        District::create(['province_id'=> 31,'name' =>'khakrez']);
        District::create(['province_id'=> 31,'name' =>'maruf']);
        District::create(['province_id'=> 31,'name' =>'maywand']);
        District::create(['province_id'=> 31,'name' =>'miyan_nasheen']);
        District::create(['province_id'=> 31,'name' =>'naish']);
        District::create(['province_id'=> 31,'name' =>'panjwaye']);
        District::create(['province_id'=> 31,'name' =>'reg']);
        District::create(['province_id'=> 31,'name' =>'shah_wali_kot']);
        District::create(['province_id'=> 31,'name' =>'shorabak']);
        District::create(['province_id'=> 31,'name' =>'spin_boldak']);
        District::create(['province_id'=> 31,'name' =>'zhari']);
        District::create(['province_id'=> 32,'name' =>'chahar_burjak']);
        District::create(['province_id'=> 32,'name' =>'chakhansur']);
        District::create(['province_id'=> 32,'name' =>'kang']);
        District::create(['province_id'=> 32,'name' =>'khash_rod']);
        District::create(['province_id'=> 32,'name' =>'zaranj']);
        District::create(['province_id'=> 33,'name' =>'chora']);
        District::create(['province_id'=> 33,'name' =>'deh_rahwod']);
        District::create(['province_id'=> 33,'name' =>'khas_uruzgan']);
        District::create(['province_id'=> 33,'name' =>'shahidi_hassas']);
        District::create(['province_id'=> 33,'name' =>'tarin_kowt']);
        District::create(['province_id'=> 34,'name' =>'atghar']);
        District::create(['province_id'=> 34,'name' =>'daychopan']);
        District::create(['province_id'=> 34,'name' =>'kakar']);
        District::create(['province_id'=> 34,'name' =>'mizan']);
        District::create(['province_id'=> 34,'name' =>'naw_bahar']);
        District::create(['province_id'=> 34,'name' =>'qalat']);
        District::create(['province_id'=> 34,'name' =>'shah_joy']);
        District::create(['province_id'=> 34,'name' =>'shamulzayi']);
        District::create(['province_id'=> 34,'name' =>'shinkay']);
        District::create(['province_id' => 34,'name' =>'tarnak_wa_jalda']);

    }
}
